apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubernetes/deployment.yaml
- kubernetes/namespace.yaml
- kubernetes/service.yaml
namespace: api
secretGenerator:
- name: api
  envs:
  - .env
patches:
- target:
    kind: Deployment
    name: api
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
        - secretRef:
            name: api
