apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: ghcr.io/sleepycat/fp4-api:latest
        name: fp4-api
        ports:
        - containerPort: 3000
        resources: {}
status: {}
